---
title: "Pre-COVID19_Gold"
author: "Suyeon Song"
date: "2024-04-15"
output: html_document
---

# S&P 500

```{r}
# S&P 500 data loading
library(quantmod)
getSymbols("SPY",
  src = "yahoo",
  from = "2014-01-01",
  to = "2024-04-16")
sp500 <- na.omit(Cl(SPY))
colnames(sp500) <- "close"
sp500_df <- data.frame(
  date = index(sp500),
  close = as.numeric(sp500$close))
sp500_df$date <- as.Date(sp500_df$date, format = "%m/%d/%Y")
sp500_df <- sp500_df[order(sp500_df$date), ]

```

# Gold 

```{r}
library(quantmod)
getSymbols("GC=F",
  src = "yahoo",
  from = "2014-01-01", to = "2024-04-16")
gold <- na.omit(Cl(`GC=F`))
colnames(gold) <- "close"
gold_df <- data.frame(
  date = index(gold),
  close = as.numeric(gold$close))
gold_df$date <- as.Date(gold_df$date, format = "%m/%d/%Y")
gold_df <- gold_df[order(gold_df$date), ]
gold_ts <- ts(gold)
plot(gold_df$date, gold_ts,
  main = "Time Seris of Gold Price (Closing Value)",
  type = "l", xlab = "Date", ylab = "Gold Price")
```

```{r}
par(mfrow=c(1,2))
acf(gold_ts, main = "ACF plot of Gold")
pacf(gold_ts, main = "PACF plot of Gold")
```

# T-bill

```{r}
# 10 years of t-bill data loading
tb_2014 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2014.csv")
tb_2015 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2015.csv")
tb_2016 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2016.csv")
tb_2017 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2017.csv")
tb_2018 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2018.csv")
tb_2019 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2019.csv")
tb_2020 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2020.csv")
tb_2021 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2021.csv")
tb_2022 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2022.csv")
tb_2023 <- read.csv("/Users/suyeonsong/TimeSeries-Project/t-bill/2023.csv")
```

```{r}
# extract a column of "X13.WEEKS.COUPON.EQUIVALENT"
cp_2014 <- (tb_2014[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2015 <- (tb_2015[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2016 <- (tb_2016[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2017 <- (tb_2017[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2018 <- (tb_2018[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2019 <- (tb_2019[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2020 <- (tb_2020[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2021 <- (tb_2021[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2022 <- (tb_2022[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
cp_2023 <- (tb_2023[, c("Date", "X13.WEEKS.COUPON.EQUIVALENT")])
```

```{r}
# set the date type in ascending order
cp_2014 <- cp_2014[order(cp_2014$Date), ]
cp_2015 <- cp_2015[order(cp_2015$Date), ]
cp_2016 <- cp_2016[order(cp_2016$Date), ]
cp_2017 <- cp_2017[order(cp_2017$Date), ]
cp_2018 <- cp_2018[order(cp_2018$Date), ]
cp_2019 <- cp_2019[order(cp_2019$Date), ]
cp_2020 <- cp_2020[order(cp_2020$Date), ]
cp_2021 <- cp_2021[order(cp_2021$Date), ]
cp_2022 <- cp_2022[order(cp_2022$Date), ]
cp_2023 <- cp_2023[order(cp_2023$Date), ]
```

```{r}
# list them all
cp_list <- list(
  cp_2014 = cp_2014, cp_2015 = cp_2015, cp_2016 = cp_2016,
  cp_2017 = cp_2017, cp_2018 = cp_2018, cp_2019 = cp_2019,
  cp_2020 = cp_2020, cp_2021 = cp_2021, cp_2022 = cp_2022,
  cp_2023 = cp_2023)
```

```{r}
library(dplyr)
df_merge <- lapply(cp_list, function(df) {
  # sort by date
  df <- df[order(as.Date(df$Date, format = "%m/%d/%Y")), ]
  # rename columns
  colnames(df) <- c("date", "coupon")
  # convert date type
  df$date <- as.Date(df$date, format = "%m/%d/%Y")
  return(df)})

names(df_merge) <- names(cp_list)
combined_df <- bind_rows(df_merge)
```

```{r}
tmp <- inner_join(sp500_df, gold_df, by = "date")
df <- inner_join(tmp, combined_df, by = "date")
print(nrow(df))
colnames(df) <- c("date", "sp500", "gold", "coupon")
str(df)
```
```{r}
library(dplyr)
df_filtered <- df %>%
  filter(date >= "2014-01-01" & date <= "2020-01-01")
```

```{r}
library(forecast)
gold <- df_filtered$gold
gold_ts <- ts(gold,
  start = c(2014, 1),
  frequency = 249)

plot(gold_ts,
  main = "Gold price over time (2014-2019)",
  ylab = "Gold price")

gold.dat <- df$gold
gold.dat_ts <- ts(
  gold.dat,
  start = c(2014, 1),
  frequency = 249)
plot(gold.dat_ts,
  main = "Gold price over time (2014-2024)",
  ylab = "Gold price")
```
```{r}
# 1st order diff
gold_diff <- diff(gold, 1)
tsdisplay(gold_diff,
  points = F,
  main = "Lag-1 Differenced Gold",
  xlab = "Date",
  ylab = "Differencing of Gold",
  col = "black")

monthplot(gold_diff,
  main = "Monthly plot of Lag-1 Differenced Gold")
```

```{r}
gold_model <- auto.arima(
  gold_ts,
  max.p = 5, max.q = 5,
  max.order = 10, stationary = F, seasonal = F,
  trace = T, stepwise = F, approximation = F)
```


```{r}
fitted1 <- gold_ts - gold_model$resid
range_df <- data.frame(
  Date = df_filtered$date,
  Gold = gold_ts, Fitted = fitted1)
print(range_df)
plot(range_df$Date, range_df$Gold,
  type = "l", col = "black",
  main = "Plot of Fitted vs. Actual (ARIMA (5,1,5))",
  xlab = "Date", ylab = "Gold Price")
lines(range_df$Date, range_df$Fitted, col = "red")

cor_value <- round(cor(gold, fitted1, use = "complete.obs"), 3)
plot(gold, fitted1,
  xlab = "Acutal",
  ylab = "Predicted", col = "black", pch = 20,
  main = "Plot of Predicted vs. Actual")
abline(0, 1, col = "red")
text_x <- min(gold) + 0.1 * (max(gold) - min(gold))
text_y <- min(fitted1) + 0.9 * (max(fitted1) - min(fitted1))
text(
  x = text_x, y = text_y,
  labels = paste("Correlation:", cor_value),
  col = "blue")


```


```{r}
tsdisplay(gold_model$resid,
  points = F,
  main = "Residuals of ARIMA Model (5,1,5)",
  lag.max = 20)
qqnorm(gold_model$resid, main = 
          "Normal Q-Q plot (ARIMA (5,1,5))")
qqline(gold_model$resid, col = "red")
```

```{r}
library(forecast)
forecast_values <- forecast(gold_model, h = 1498)
forecast_dates <- seq(
  from = max(df_filtered$date) + 1, by = "day",
  length.out = 1498)
actual_data <- gold_df[gold_df$date >= as.Date("2014-01-01") & 
                         gold_df$date <= as.Date("2023-12-31"), ]
combined_x_range <- range(actual_data$date, forecast_dates, na.rm = TRUE)
combined_y_range <- range(actual_data$close, forecast_values$mean,
  forecast_values$lower,
  forecast_values$upper,
  na.rm = TRUE)
plot(actual_data$date, actual_data$close,
  type = "l", lwd = 1, col = "black",
  xlab = "Date", ylab = "Gold Price", 
  main = "Forecast vs. Actual Gold Prices",
  xlim = combined_x_range, ylim = combined_y_range)
lines(forecast_dates, forecast_values$mean, col = "red", lwd = 1)
lines(forecast_dates, forecast_values$lower[, 2],
  col = "blue", lty = 2) # 95% lower CI
lines(forecast_dates, forecast_values$upper[, 2],
  col = "blue", lty = 2) # 95% upper CI
abline(v = as.Date("2020-01-01"), col = "grey", lwd = 1, lty = 2)
legend("topleft",
  legend = c("Actual", "Forecast", "95% Confidence Interval"),
  col = c("black", "red", "blue"),
  lty = c(1, 1, 2), lwd = c(1, 1, 1))

plot(forecast_values)
```
